name: Test CI

on:
  pull_request:
  workflow_dispatch:

jobs:
   test-installer:
      runs-on: ${{ matrix.os }}
      strategy:
          matrix:
            os: [macos-latest, ubuntu-latest, windows-latest]
      steps:
        - name: Install Node.js, NPM and Yarn
          uses: actions/setup-node@v1
          with:
            node-version: 14
        - run: npm install -g depp-installer
        - run: depp --help